name: "InverterToHa"
description: "Bridge tra i dispositivi 485 e HA"
version: "1"
slug: "InverterToHa"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: application
options:
  serialdev: null
  debug: false
  mqttserver= "localhost"
  mqttserverport: 1388
  mqttuser: homeassistant
  mqttpwd=: ""



schema:
  serialdev: device(subsystem=tty)
  debug: bool
  mqttserver: str
  mqttserverport: int
  mqttuser: str
  mqttpwd=: password

