name: "solar"
description: "Bridge tra i dispositivi 485 e HA"
version: "4"
slug: "solar"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: application
options:
  serialdev: "core-mosquitto"
  debug: false
  mqttserver: "localhost"
  mqttserverport: 1883
  mqttuser: "validuser"
  mqttpwd: ""
schema:
  serialdev: device(subsystem=tty)
  debug: bool
  mqttserver: str
  mqttserverport: int
  mqttuser: str
  mqttpwd: password

